# This is the configuration used to check the rubocop source code.

AllCops:
  Include:
    - '*.lic'

Style/BlockComments:
  Enabled: false

# We will want to enable this Cop once the code is in a better state
Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/LineLength:
  Enabled: false
