---
# moves to use to fill time while aiming
# stops as soon as best shot possible is seen
aim_fillers:
  Crossbow:
  - bob
  - bob
  Bow:
  - bob
  - bob
  - bob
aim_fillers_stealth:
  Bow:
  - bob
  - hide
  - bob
  Crossbow:
  - bob
  - hide
lootables:
# things to pick up off the ground
# ammunition
- bolt
- arrow
- rock
# valuable loot
- coin
- map
- scroll
- bark
- parchment
# gems
- tsavorite
- zircon
- quartz
- chalcedony
- diopside
- coral
- moonstone
- onyx
- topaz
- amber
- pearl
- chryso
- lazuli
- turquoise
- bloodstone
- hematite
- morganite
- sapphire
- agate
- carnelian
- diamond
- crystal
- emerald
- ruby
- tourmaline
- tanzanite
- jade
- ivory
- sunstone
- iolite
- beryl
- garnet
- alexandrite
- amethyst
- citrine
- aquamarine
- star-stone
- crystal
- kunzite
- stones
- spinel
- opal
- peridot
- andalusite
stances:
# custom stances to prevent trying to parry with ranged weapons
  Bow:
  - evasion
  - shield
  Crossbow:
  - evasion
  - shield
  Slings:
  - evasion
  - shield
  Offhand Weapon:
  - evasion
  - shield
skinning:
# skinning behavior. If you don't wear a bundle skins will drop to the ground
  skin: true
  arrange_all: false
  arrange_count: 0
# what cambrinth do you wear and how much does it hold
cambrinth: armband
cambrinth_cap: 32
# do you need to hold it to charge it?
held_cambrinth: false
# If you cast spells for training make sure their prep and cast messages are
# recorded here
cast_messages:
- ^You gesture
- You reach with both
- You listen intently to the air
- You close your eyes
- You close yours eyes
- Your target pattern dissipates
- You make a holy gesture
- You raise your left hand skyward
- Flickering shadows tear away
- You sense a Malediction
- You release an accompaniment
- You roll your hands in an elliptical pattern
- You cup your hand
prep_messages:
- You begin chanting a psalm
- With meditative movements you
- You raise your head skyward
- With tense movements
- You trace (an|a) (.*) sigil in the air
- Slow, rich tones form
charged_maneuvers:
  Brawling: palmstrike
  Bow: powershot
  Crossbow: powershot
  Slings: powershot
  Small Edged: cleave
  Large Edged: cleave
  Twohanded Edged: cleave
  Small Blunt: crash
  Large Blunt: crash
  Twohanded Blunt: crash
  Staves: twirl
  Polearms: impale
# Number of enemies to let build up before trying to kill them
dance_threshold: 0
# weapon skill to use while dancing
dance_skill: Small Edged
# actions to use while dancing
dance_actions:
- analyze
- feint
- bob
# abilities to train while fighting and their cooldown in seconds
training_abilities:
  Hunt:
    :check: Perception
    :cooldown: 80
fatigue_regen_threshold: 90
fatigue_regen_action: bob
# cooldown timers between attempts to train a skill
# TODO remove timer field and store in uservars
exp_timers:
  Stealth:
    cooldown: 300
    timer:
  First Aid:
    cooldown: 360
    timer:
  Locksmithing:
    cooldown: 600
    timer:
  Theurgy:
    cooldown: 720
    timer:
  Thievery:
    cooldown: 3600
    timer:
  Attunement:
    cooldown: 130
    timer:
  Summoning:
    cooldown: 120
    timer:
# this scaling factor is multiplied by your discerned max mana for a spell
# it rounds up so anything < 1 will always result in one mana removed
prep_scaling_factor: 0.98
# listen to classes?
listen: true

forge_container: backpack
forge_hammer: diagonal-peen

safe_room: 851

hide_to_steal: true

# what to remove for braiding
hand_armor: gloves

# should crossing training idle or exit when all skills are above 28/34?
exit_on_skills_capped: false