---
# See https://github.com/rpherbig/dr-scripts/wiki/YAML-Settings for documentation




# Combat settings
aim_fillers:
  Crossbow:
  - bob
  - bob
  Bow:
  - bob
  - bob
  - bob
  Slings:
  - bob
  - bob
  - bob
stances:
  Bow:
  - evasion
  - shield
  Crossbow:
  - evasion
  - shield
  Slings:
  - evasion
  - shield
  Offhand Weapon:
  - evasion
  - shield
stance_override:
skinning:
  skin: true
  arrange_all: false
  arrange_count: 0
  tie_bundle: false
charged_maneuvers:
  Brawling: palmstrike
  Bow: powershot
  Crossbow: powershot
  Slings: powershot
  Small Edged: cleave
  Large Edged: cleave
  Twohanded Edged: rush
  Small Blunt: crash
  Large Blunt: crash
  Twohanded Blunt: crash
  Staves: twirl
  Polearms: impale
dance_threshold: 0
dance_skill: Small Edged
dance_actions:
- analyze
- feint
- bob
manipulate_threshold:
training_abilities:
  Hunt:
    :check: Perception
    :cooldown: 80
fatigue_regen_threshold: 90
fatigue_regen_action: bob
summoned_weapons:
summoned_weapons_element:
summoned_weapons_ingot:
buff_spells:
offensive_spells:
aim_fillers_stealth:
buff_nonspells:
dance_actions_stealth:
thanatology:
weapon_training:
combat_trainer_target_increment: 3
combat_trainer_action_count: 10
dual_load: false
is_empath: false
use_stealth_attacks: false
backstab:
ambush: false
performance_monitor_weapons:
retreat_threshold:




# Hunting settings
escort_zones:
  # https://elanthipedia.play.net/mediawiki/index.php/Giant_black_leucro
  leucro1:
    base: 1176
    area: wilds
    enter: leucro1
  leucro2:
    base: 1176
    area: wilds
    enter: leucro2
  # https://elanthipedia.play.net/mediawiki/index.php/Forest_geni
  geni:
    base: 1176
    area: wilds
    enter: geni
  # https://elanthipedia.play.net/mediawiki/index.php/Rock_guardian
  rock_guardians:
    base: 1176
    area: northern_trade
    enter: rock_guardians
  # https://elanthipedia.play.net/mediawiki/index.php/Giant_thicket_viper
  thicket_vipers:
    base: 1176
    area: northern_trade
    enter: thicket_vipers
hunting_zones:
  # https://elanthipedia.play.net/mediawiki/index.php/Rat
  rats:
  - 6049
  - 6048
  - 6047
  - 6046
  - 6050
  - 6053
  - 6054
  # https://elanthipedia.play.net/mediawiki/index.php/Sleazy_Lout
  louts:
  - 686
  - 687
  - 688
  - 19199
  - 690
  #https://elanthipedia.play.net/mediawiki/index.php/Origami_Creature
  origami:
  - 8433
  - 8434
  - 8430
  - 8431
  - 8429
  - 8428
  - 8427
  - 8426
  # https://elanthipedia.play.net/mediawiki/index.php/Musk_Hog
  hogs:
  - 1438
  - 1439
  - 1440
  - 1441
  - 1442
  - 1443
  - 1444
  - 1445
  - 1446
  - 1447
  - 1448
  # https://elanthipedia.play.net/mediawiki/index.php/Forager_goblin
  # https://elanthipedia.play.net/mediawiki/index.php/Field_Goblin
  # https://elanthipedia.play.net/mediawiki/index.php/Scavenger_goblin
  goblins:
  - 1473
  - 1479
  - 1483
  - 1480
  - 1481
  - 1486
  - 1482
  # https://elanthipedia.play.net/mediawiki/index.php/S%27lai_Scout
  scouts: # This is about half of the area
  - 7292
  - 7293
  - 7294
  - 7295
  - 7296
  - 7297
  - 7298
  - 7299
  # https://elanthipedia.play.net/mediawiki/index.php/Faenrae_reaver
  # https://elanthipedia.play.net/mediawiki/index.php/Wind_Hound
  reavers:
  - 1850
  - 1851
  - 1852
  - 1856
  - 1848
  - 1849
  # https://elanthipedia.play.net/mediawiki/index.php/Rock_Troll_(1)
  rock_trolls:
  - 8946
  - 8947
  - 8954
  - 8955
  - 8948
  - 8949
  # https://elanthipedia.play.net/mediawiki/index.php/Snowbeast
  snowbeasts: # 2264 causes a loop, do not use
  - 2255
  - 2268
  - 2263
  - 2256
  - 2265
  - 2266
  - 2272
  - 2259
  - 2260
  - 2262
  - 2267
  - 2269
  - 2270
  - 2261
  # https://elanthipedia.play.net/mediawiki/index.php/Young_Ogre
  young_ogres:
  - 1588
  - 1591
  - 1592
  - 1593
  - 1590
  - 1589
  - 1587
  # https://elanthipedia.play.net/mediawiki/index.php/Fire_Sprite
  fire_sprites1: # 80-100 Locksmithing/Skinning
  - 1770
  - 1771
  - 1772
  - 1773
  - 1774
  - 1775
  - 1776
  - 1777
  - 1778
  # https://elanthipedia.play.net/mediawiki/index.php/Dire_Bear
  dire_bears: # 1555 is bugged, do not use
  - 1563
  - 1565
  - 1582
  - 1581
  - 1578
  - 1566
  thugs: # 110-150 Locksmithing
  - 6091
  - 6092
  - 6097
  - 6097
  # https://elanthipedia.play.net/mediawiki/index.php/Pale_Grey_Death_Spirit
  pale_gray_spirits:
  - 19384
  - 19387
  - 19390
  - 19393
  # https://elanthipedia.play.net/mediawiki/index.php/River_Sprite
  river_sprites:
  - 19754
  - 19799
  - 19847
  - 19778
  gryphons1: # first tier gryphons in Rossman's Landing.  250-350 skill range
  - 8627
  - 8626
  - 8624
  - 8625
  - 8628
  - 8629
  - 8630
  quartz_gargs:
  - 8290
  - 8291
  - 8289
  # https://elanthipedia.play.net/mediawiki/index.php/Bristle-backed_peccary
  bristle_peccs:
  - 7707
  - 7716
  - 7713
  - 7706
  - 7719
  # https://elanthipedia.play.net/mediawiki/index.php/Lesser_Dusky-Scaled_Basilisk
  dusky_basilisk:
  - 19435
  - 19436
  - 19437
  - 19438
  # https://elanthipedia.play.net/mediawiki/index.php/Armored_warklin
  # https://elanthipedia.play.net/mediawiki/index.php/Warklin_mauler
  warklin:
  - 7272
  - 7273
  - 7274
  - 7275
  - 7276
  - 7277
  - 7278
  - 7279
  - 7271
  black_goblins:
  - 4167
  - 4168
  - 4170
  - 4169
  toads:
  - 50266
  - 50267
training_manager_hunting_priority: false
training_manager_priority_skills:
hunting_info:





# Repair settings
repair_withdrawal_amount: 10_000





# Safe-room settings
safe_room_id:
safe_room_take:
safe_room_give:
safe_room_tip_threshold:
safe_room_tip_amount:
safe_room_empath:





# Spellcasting (and Khri) settings
cambrinth: armband
cambrinth_cap: 32
held_cambrinth: false
stored_cambrinth: false
prep_messages:
- You begin chanting a psalm
- With (calm|meditative|rigid|tense) movements you
- You raise your head skyward
- With (tense|calm) movements
- You trace (an|a) (.*) sigil in the air
- Slow, rich tones form
- You begin chanting( a)? (catechisms|mantra|prayer|psalm)
- You raise (your|an) (arm|arms|head|palms) skyward
- With a sharp cut to your voice
- With a resounding "POP"
- Your skin briefly withers and tightens, becoming gaunt as the energies of
- The first gentle notes of Blessing of the Fae
- You begin to hum the
- The wailing of lost souls accompanies your preparation
cast_messages:
- ^You gesture
- You reach with both
- You listen intently to the air
- You close your eyes
- You close yours eyes
- Your target pattern dissipates
- You make a holy gesture
- You raise your left hand skyward
- Flickering shadows tear away
- You sense a Malediction
- You release an accompaniment
- You roll your hands in an elliptical pattern
- You cup your hand
- You flicker your malevolent desires towards
- You clench your hands into fists and grit your teeth
- You make a sweeping gesture with your arm
prep_scaling_factor: 0.98
khri_preps:
- With deep breaths
- Centering your mind
- Focusing your mind
- Remembering the mantra of
- Turning inwards, you find the
- Darkness is no bar to a
- Taking a deep breath
- Placing all of your thoughts
- Your hand twitches slightly
- With but a quick thought
- You calm your body and mind
- Letting your thoughts fall into
- You calm yourself with a deep breath
- Tapping into the well of mental power within
- Knowing that a dose of paranoia is healthy
- Willing your body to meet the heightened
- Purging yourself of all distractions
- Your dedicated training lends you grace
- You carefully relax your mind through
- Honing your mind and body to a single purpose
- Nothing happens
kneel_khri: false




# Looting settings
loot_additions: []
loot_subtractions: []
lootables:
# ammunition
- bolt
- arrow
- rock
# valuable loot
- coin
- coins
- map
- scroll
- vellum
- bark
- parchment
- tablet
- papyrus
- ostracon
- seishaka leaf
# gems
- tsavorite
- zircon
- quartz
- chalcedony
- diopside
- coral
- moonstone
- onyx
- topaz
- amber
- pearl
- chryso
- lazuli
- turquoise
- bloodstone
- hematite
- morganite
- sapphire
- agate
- carnelian
- diamond
- crystal
- emerald
- ruby
- tourmaline
- tanzanite
- jade
- ivory
- sunstone
- iolite
- beryl
- garnet
- alexandrite
- amethyst
- citrine
- aquamarine
- star-stone
- crystal
- kunzite
- stones
- spinel
- opal
- peridot
- andalusite
- chrysoprase
- chrysoberyl
trash_nouns:
- leaf
- pestle
- mortar
- label
- runestone
- flower
- flowers
- arrowhead
- root
- stem
- grass
- needle
- sap
- glue
- hilt
- thread
- flint
- nugget
- dira
- stems
- leaves
- bar
- lotion
- vine
- rope
- vines
- rock
# TODO: Add stick, but only if we can differentiate it from a parry stick





# Non-combat settings
exp_timers:
  Stealth:
    cooldown: 300
  First Aid:
    cooldown: 400
  Locksmithing:
    cooldown: 600
  Theurgy:
    cooldown: 720
  Thievery:
    cooldown: 600
  Attunement:
    cooldown: 130
listen: false
safe_room: 851
hide_to_steal: true
hand_armor: gloves
exit_on_skills_capped: false
crossing_training_sorcery:
crossing_training_sorcery_room: 1137
crossing_training_requires_movement:
- Appraisal
- Athletics
- Attunement
- Empathy
- Engineering
- Forging
- Outfitting
- Scouting
- Sorcery
- Stealth
- Thievery
- Theurgy
- Trading
forage_item:
braid_item:
training_spells:
train_with_spells: true
training_nonspells:
crossing_training:
use_research: false
water_holder:
flint_lighter:





# Crafting settings
crafting_container: backpack
forge_hammer: diagonal-peen
forging_tools:
- cross-peen hammer
- tong
- bellow
- shovel
knitting_tools:
- knitting needle
shaping_tools:
- carving knife
- shaper
- drawknife
- rasp
work_order_disciplines:
train_workorders:
forge_container: backpack
carving_tools:
forging_belt:
engineering_belt:
outfitting_belt:





# Mining settings

mining_rooms:
- wicked_burrow
- stone_clan
- waterfall

mining_skip_populated: true

mining_buddy_rooms:
  wicked_burrow:
  - 19079
  - 19080
  - 19081
  - 19082
  - 19084
  - 19122
  - 19123
  - 19124
  - 19088
  - 19089
  stone_clan:
  - 7262
  - 7263
  - 7264
  - 7265
  - 7266
  - 7267
# high mountains - behind the waterfall
  waterfall:
  - 19219
  - 19220
  warklins:
  - 7272
  - 7273
  - 7274
  - 7275
  - 7276
  - 7277
  - 7278
  - 7279
  - 7271
  abandoned_mine:
  - 7235
  - 7236
  - 7237
  - 7238

mining_buddy_mine_every_room: false
mining_buddy_vein_list:
# uncommon
- Silver
# rare
- Gold
- Platinum
- Lumium
- Niniam
- Electrum
- Muracite
- Darkstone
# very rare
- Damite
- Kertig
- Haralun
- Glaes
- Animite
mine_implement: shovel
mine_use_packet: true





# Lockpicking settings
stop_pick_on_mindlock: true
use_lockpick_ring: true
lockpick_type: ordinary
harvest_traps: true
picking_box_source: duffel bag
picking_box_storage: backpack
lockpick_dismantle:
lockpick_buffs:






# Sell loot settings
sell_loot_pouch: true
sell_loot_bundle: true
sell_loot_money_on_hand: 3 silver

# Misc settings
storage_containers:
gear:
gear_sets:
empath_healing:

osrel_no_harness: false
osrel_amount:

spare_gem_pouch_container:
gem_pouch_adjective:

workorder_diff: challenging